version: '3.0'
services:
  foo:
    build: .
    depends_on:
      - jaeger-aio
    ports:
      - "9292:9292"
    networks:
      - traces
    environment:
      - JAEGER_HOST=http://jaeger-aio:14268/api/traces
  jaeger-aio:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "14268:14268"
      - "16686:16686"
    networks:
      - traces
networks:
  traces:
