---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-otel-demo
  labels:
    app: sinatra-otel-demo
spec:
  template:
    spec:
      containers:
        - image: genebean/sinatra-otel-demo:latest
          imagePullPolicy: Always
          name: sinatra-otel-demo
          ports:
            - http: 9292
          env:
            - name: DD_TRACE_AGENT_URL
              value: '{{ .Values.ddagent.url }}'
---
apiVersion: v1
kind: Service
metadata:
  name: sinatra-otel-demo
spec:
  ports:
    - port: 9292
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sinatra-otel-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: sinatra-otel-demo
spec:
  rules:
    - host: {{ .Values.fqdn }}
      http:
        paths:
          - backend:
              serviceName: sinatra-otel-demo
              servicePort: http
            path: /
  tls:
    - hosts:
        - {{ .Values.fqdn }}
      secretName: '{{ .Values.fqdn }}-tls'

